# Generated by Django 2.2.16 on 2020-11-18 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=16)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(default='', max_length=50)),
                ('office', models.CharField(default='', max_length=20)),
                ('rating_class', models.CharField(default='average', max_length=20)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('num_ratings', models.IntegerField(null=True)),
                ('rmp_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=16)),
                ('campus', models.CharField(default='College Station', max_length=16)),
                ('user_saved', models.BooleanField(default=False)),
                ('avg_starttime', models.TimeField(default='12:00:00')),
                ('avg_endtime', models.TimeField(default='15:00:00')),
                ('avg_day_length', models.TimeField(default='05:00:00')),
                ('free_on_monday', models.BooleanField(default=False)),
                ('free_on_tuesday', models.BooleanField(default=False)),
                ('free_on_wednesday', models.BooleanField(default=False)),
                ('free_on_thursday', models.BooleanField(default=False)),
                ('free_on_friday', models.BooleanField(default=False)),
                ('num_free_days', models.IntegerField(default=0)),
                ('activities', models.ManyToManyField(to='api.Activity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_A', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_B', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_C', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_D', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_F', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_Q', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Professor')),
            ],
            options={
                'unique_together': {('course', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='Activity_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('day', models.CharField(max_length=8)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Activity')),
                ('term', models.CharField(max_length=32)),
                ('section_num', models.IntegerField()),
                ('crn', models.IntegerField()),
                ('credit_hours', models.IntegerField()),
                ('campus', models.CharField(default='College Station', max_length=64)),
                ('honors', models.BooleanField(default=False)),
                ('web', models.BooleanField(default=False)),
                ('total_seats', models.IntegerField(default=0)),
                ('seats_taken', models.IntegerField(default=0)),
                ('interested_students', models.IntegerField(default=0)),
                ('course_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course_Prof')),
            ],
            options={
                'unique_together': {('course_prof', 'term', 'section_num')},
            },
        ),
    ]
