# Generated by Django 2.2.16 on 2020-11-05 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=20)),
                ('rating_class', models.CharField(max_length=20)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('num_ratings', models.IntegerField(null=True)),
                ('rmp_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('activities', models.ManyToManyField(to='api.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_A', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_B', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_C', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_D', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_F', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percent_Q', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Professor')),
            ],
            options={
                'unique_together': {('course', 'professor')},
            },
        ),
        migrations.CreateModel(
            name='Blocked_Time_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Activity')),
                ('term', models.CharField(max_length=20)),
                ('section_num', models.IntegerField()),
                ('crn', models.IntegerField()),
                ('credit_hours', models.IntegerField()),
                ('honors', models.BooleanField(default=False)),
                ('web', models.BooleanField(default=False)),
                ('total_seats', models.IntegerField(default=0)),
                ('seats_taken', models.IntegerField(default=0)),
                ('interested_students', models.IntegerField(default=0)),
                ('course_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course_Prof')),
            ],
        ),
        migrations.AddConstraint(
            model_name='blocked_time_activity',
            constraint=models.UniqueConstraint(fields=('user', 'term'), name='unique_user_term_blocked_time'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course_prof', 'term', 'section_num')},
        ),
    ]
