# Generated by Django 2.2.16 on 2020-11-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blocked_Time_Activity',
        ),
    ]
