# Generated by Django 2.2.16 on 2020-10-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=20)),
                ('rate_my_prof', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.CreateModel(
            name='Course_Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_A', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_B', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_C', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_D', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_F', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_Q', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Professor')),
            ],
            options={
                'unique_together': {('course', 'professor')},
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='activities',
            field=models.ManyToManyField(to='api.Activity'),
        ),
        migrations.CreateModel(
            name='Activity_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
            ],
            options={
                'unique_together': {('activity', 'day', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Activity')),
                ('term', models.CharField(max_length=20)),
                ('section_num', models.IntegerField()),
                ('honors', models.BooleanField()),
                ('course_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course_Prof')),
            ],
            options={
                'unique_together': {('course_prof', 'term', 'section_num')},
            },
        ),
    ]
