# Generated by Django 2.2.16 on 2020-10-16 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schedule_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_instance',
            old_name='time',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='activity_instance',
            name='starttime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activity_instance',
            unique_together=set(),
        ),
    ]
