# Generated by Django 2.2.16 on 2020-11-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201107_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.AddField(
            model_name='schedule',
            name='avg_day_length',
            field=models.TimeField(default='03:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='avg_endtime',
            field=models.TimeField(default='15:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='avg_starttime',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='free_on_friday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='free_on_monday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='free_on_thursday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='free_on_tuesday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='free_on_wednesday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='campus',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity_instance',
            name='day',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='activity_instance',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='term',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='section',
            name='term',
            field=models.CharField(max_length=32),
        ),
    ]
