# Generated by Django 2.2.16 on 2020-10-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201016_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='rate_my_prof',
            new_name='RMP_link',
        ),
        migrations.AddField(
            model_name='professor',
            name='overall_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='total_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='CRN',
            field=models.IntegerField(default=99999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='credit_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='interested_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='seats_taken',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='total_seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='web',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
