# Generated by Django 2.2.16 on 2020-10-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201031_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='RMP_link',
            new_name='rmp_link',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='CRN',
            new_name='crn',
        ),
        migrations.AlterField(
            model_name='section',
            name='honors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='seats_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='web',
            field=models.BooleanField(default=False),
        ),
    ]
