# Generated by Django 2.2.16 on 2020-11-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201108_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='campus',
            field=models.CharField(default='College Station', max_length=16),
            preserve_default=False,
        ),
    ]
