# Generated by Django 2.2.16 on 2020-10-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201031_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='total_ratings',
            new_name='num_ratings',
        ),
        migrations.AddField(
            model_name='professor',
            name='rating_class',
            field=models.CharField(default='average', max_length=20),
            preserve_default=False,
        ),
    ]
