# Generated by Django 2.2.16 on 2020-11-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201031_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='term',
            field=models.CharField(default='FALL 2020', max_length=20),
            preserve_default=False,
        ),
    ]
