# Generated by Django 2.2.16 on 2020-11-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_schedule_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='dept',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='office',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professor',
            name='rating_class',
            field=models.CharField(default='average', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='campus',
            field=models.CharField(default='College Station', max_length=64),
        ),
    ]
