# Generated by Django 2.2.16 on 2020-11-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201108_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='campus',
            field=models.CharField(default='College Station', max_length=16),
        ),
    ]
