# Generated by Django 2.2.16 on 2020-11-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201108_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user_saved',
            field=models.BooleanField(default=False),
        ),
    ]
