# Generated by Django 2.2.16 on 2020-11-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_schedule_user_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.AddField(
            model_name='schedule',
            name='num_free_days',
            field=models.IntegerField(default=0),
        ),
    ]
